# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

export HISTIGNORE="explorer:where:which:clear:bash:exit:ls:ll:size:gl:glog:gla:ga:gs:gco:gcb:exit:clear:git log:git pull:git push"
export HISTCONTROL=ignoredups

export HISTSIZE=5000
export HISTFILESIZE=${HISTSIZE}